version: "3"

services:
  7d2d:
    image: kromix/7d2d
    container_name: 7d2d
    volumes:
      - data:/home/steam/server/
      - save:/root/.local/share/7DaysToDie/Saves/
    networks:
      7d2d:
        ipv4_address: 172.30.0.2
    ports:
      - 8090:8080
      - 8091:8081
      - 26900-26902:26900-26902/udp
      - 26900:26900/tcp
    restart: unless-stopped

volumes:
  data:
  save:

networks:
  7d2d:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/30
